// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UniRx;
using UnityEngine;


public abstract class CharacterControllerBase : Controller {
    
    public abstract void InitializeCharacter(CharacterViewModel character);
    
    public override ViewModel CreateEmpty() {
        return new CharacterViewModel(this);
    }
    
    public virtual CharacterViewModel CreateCharacter() {
        return ((CharacterViewModel)(this.Create()));
    }
    
    public override void Initialize(ViewModel viewModel) {
        this.InitializeCharacter(((CharacterViewModel)(viewModel)));
    }
}
