// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UniRx;


[DiagramInfoAttribute("RunningGuyGame")]
public abstract class CharacterViewBase : ViewBase {
    
    public override System.Type ViewModelType {
        get {
            return typeof(CharacterViewModel);
        }
    }
    
    public CharacterViewModel Character {
        get {
            return ((CharacterViewModel)(this.ViewModelObject));
        }
        set {
            this.ViewModelObject = value;
        }
    }
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<CharacterController>());
    }
    
    protected override void InitializeViewModel(ViewModel viewModel) {
        CharacterViewModel character = ((CharacterViewModel)(viewModel));
    }
}

public class CharacterAvatarViewViewBase : CharacterViewBase {
    
    private IDisposable _MovementIntentionDisposable;
    
    [UFToggleGroup("MovementState")]
    [UnityEngine.HideInInspector()]
    [UFRequireInstanceMethod("MovementStateChanged")]
    public bool _BindMovementState = true;
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<CharacterController>());
    }
    
    /// Subscribes to the state machine property and executes a method for each state.
    public virtual void MovementStateChanged(Invert.StateMachine.State value) {
        if (value is Idle) {
            this.OnIdle();
        }
        if (value is MoveLeft) {
            this.OnMoveLeft();
        }
        if (value is MoveRight) {
            this.OnMoveRight();
        }
    }
    
    public virtual void OnIdle() {
    }
    
    public virtual void OnMoveLeft() {
    }
    
    public virtual void OnMoveRight() {
    }
    
    public virtual void ResetMovementIntention() {
        if (_MovementIntentionDisposable != null) _MovementIntentionDisposable.Dispose();
        _MovementIntentionDisposable = GetMovementIntentionObservable().Subscribe(Character._MovementIntentionProperty).DisposeWith(this);
    }
    
    protected virtual MovementIntention CalculateMovementIntention() {
        return default(MovementIntention);
    }
    
    protected virtual UniRx.IObservable<MovementIntention> GetMovementIntentionObservable() {
        return this.UpdateAsObservable().Select(p => CalculateMovementIntention());
    }
    
    public override void Bind() {
        base.Bind();
        ResetMovementIntention();
        if (this._BindMovementState) {
            this.BindProperty(Character._MovementStateProperty, this.MovementStateChanged);
        }
    }
}

public partial class CharacterAvatarView : CharacterAvatarViewViewBase {
}
